#!/usr/bin/env bash
set -euo pipefail

if git config --global --get hook.hk-pre-push.command >/dev/null; then
  git config --local --unset-all hook.hk-pre-push.command || true
  git config --local --unset-all hook.hk-pre-push.event || true
  git config --local --unset-all hook.hk-pre-push.enabled || true
else
  hk install --mise
fi
